### ISSUE TITLE
Request for more Education Lessons Pack

### ISSUE THREAD

**Issue by Cooolaid** [pkulchenko/ZeroBraneEduPack#4]
Is it possible you can create more LUA lessons ?
more for the very very beginners type.
Specially for Syntaxing., Tables and Functions.

the ones in Zerobrane, im told are for Lua 5.0 and 5.1 but not for newer changes of lua 5.3
Unless Im misinformed.
The Education Pack date says its 3 years old. hence the reason why I am asking.
Thanks

**Comment by dvdvideo1234** [comment]
Done.

**Comment by pkulchenko** [comment]
Thanks @dvdvideo1234!

@Cooolaid, all the examples should run under Lua 5.1, Lua 5.2 and Lua 5.3, although they don't cover Lua 5.3-specific features, like bit operations.

**Comment by pkulchenko** [comment]
I've also added `quick-start.lua` (which covers tables, functions, and general syntax) and updated it for Lua 5.3 changes.
